#!/bin/sh
set -e

. `dirname $0`/assert.sh

# Workaround for https://bugs.debian.org/1050256
mkdir -p /run/systemd/system/service.d
cat <<EOF>/run/systemd/system/service.d/disable-private-network.conf
[Service]
PrivateNetwork=no
EOF
systemctl daemon-reload

ORIG_HOST=`cat /etc/hostname`
echo "original hostname: $ORIG_HOST"

# should activate daemon and work
STATUS="`hostnamectl`"
assert_in "Static hostname: $ORIG_HOST" "$STATUS"
assert_in "Kernel:.* `uname -r`" "$STATUS"

# change hostname
assert_eq "`hostnamectl set-hostname testhost 2>&1`" ""
assert_eq "`cat /etc/hostname`" "testhost"
assert_in "Static hostname: testhost" "`hostnamectl`"

# reset to original
assert_eq "`hostnamectl set-hostname $ORIG_HOST 2>&1`" ""
assert_eq "`cat /etc/hostname`" "$ORIG_HOST"
assert_in "Static hostname: $ORIG_HOST" "`hostnamectl`"
