#!/bin/sh
set -e
# Default KillUserProcesses should be off for debian/ubuntu builds
r=$(busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager KillUserProcesses)
[ "b false" = "$r" ]
