#!/bin/sh
set -e

# Workaround for https://bugs.debian.org/1050256
mkdir -p /run/systemd/system/service.d
cat <<EOF>/run/systemd/system/service.d/disable-private-network.conf
[Service]
PrivateNetwork=no
EOF
systemctl daemon-reload

exec test/networkd-test.py
