#!/bin/sh
# autopkgtest check: Run upstream udev test script
# (C) 2016 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
set -euC

TEST_DIR=${AUTOPKGTEST_TMP:=$(mktemp -d)}
mkdir -p $TEST_DIR/test
test/sys-script.py $TEST_DIR/test
cp test/udev-test.pl $TEST_DIR
if [ -f /usr/lib/systemd/tests/unit-tests/manual/test-udev ]; then
    cp /usr/lib/systemd/tests/unit-tests/manual/test-udev $TEST_DIR
elif [ -f /usr/lib/systemd/tests/manual/test-udev ]; then
    cp /usr/lib/systemd/tests/manual/test-udev $TEST_DIR
else
    echo "test-udev not found!"
    exit 1
fi
cd $TEST_DIR
./udev-test.pl
