#!/bin/sh
# run upstream system integration tests
# Author: Martin Pitt <martin.pitt@ubuntu.com>
set -e

DPKGARCH=$(dpkg --print-architecture)

# The build directory is used to cache the image
mkdir -p build
export BUILD_DIR="${PWD}/build"

# modify the image build scripts to install systemd from the debs instead of
# from a "make/ninja install" as we don't have a built tree here. Also call
# systemd-nspawn from the system.
sed -i '/DESTDIR.* install/ s%^.*$%    for p in `grep ^Package: '`pwd`'/debian/control | cut -f2 -d\\  |grep -Ev -- "-(udeb|dev)"`; do (cd /tmp; apt-get download $p \&\& dpkg-deb --fsys-tarfile ${p}[._]*deb | tar -C $initdir --dereference -x); done%; s_[^" ]*/systemd-nspawn_systemd-nspawn_g; s/\(_ninja_bin=\).*/\1dummy-ninja/' test/test-functions

# Because this test is used both by upstream and by Debian, we use different deny-list filenames.
# For more details see https://salsa.debian.org/systemd-team/systemd/merge_requests/52
# The naming is transitioning from blacklist to deny-list, so currently both are supported
# More details in https://github.com/systemd/systemd/pull/16262
if [ -n "$TEST_UPSTREAM" ]; then
    denylist="deny-list-ubuntu-ci"
    blacklist="blacklist-ubuntu-ci"
else
    denylist="deny-list-upstream-ci"
    blacklist="blacklist-upstream-ci"
fi

BLACKLIST_MARKERS="$blacklist-$DPKGARCH $blacklist" \
ARTIFACT_DIRECTORY=$AUTOPKGTEST_ARTIFACTS \
TEST_SHOW_JOURNAL=warning \
exec test/run-integration-tests.sh
