#!/bin/sh
# run upstream system integration tests
# Author: Martin Pitt <martin.pitt@ubuntu.com>
set -e

DPKGARCH=$(dpkg --print-architecture)

# Because this test is used both by upstream and by Debian, we use different deny-list filenames.
# For more details see https://salsa.debian.org/systemd-team/systemd/merge_requests/52
if [ -n "$TEST_UPSTREAM" ]; then
    denylist="deny-list-ubuntu-ci"
else
    denylist="deny-list-upstream-ci"
fi

export DENY_LIST_MARKERS="$denylist-$DPKGARCH $denylist"
export ARTIFACT_DIRECTORY=$AUTOPKGTEST_ARTIFACTS
export TEST_SHOW_JOURNAL=warning
export TEST_REQUIRE_INSTALL_TESTS=0
export TEST_PREFER_NSPAWN=1
export NO_BUILD=1
export QEMU_TIMEOUT=2400
export NSPAWN_TIMEOUT=2400
test/run-integration-tests.sh
