[DEFAULT]
pristine-tar = True
patch-numbers = False
sign-tags = True
debian-branch = ubuntu-plucky
debian-tag = ubuntu/%(version)s
upstream-branch = upstream/latest

[import-orig]
upstream-vcs-tag = v%(version%~%-)s

[dch]
full = True
multimaint-merge = True
customizations = debian/extra/wrap_cl.py
git-log = --first-parent
